### ISSUE TITLE
Version 1.0.0 released

### ISSUE THREAD

**Issue by ttulka** [flyway/flyway-ant#1]
Hi @axelfontaine 
I've just release the plugin, I created Wiki pages as the doc https://github.com/flyway/flyway-ant/wiki
Please let me know if anything isn't okay.
Thank you!

**Comment by axelfontaine** [comment]
Looks great! Consider linking to the wiki from the main readme to make people aware there is more documentation over there.

**Comment by ttulka** [comment]
The link added, thank you!

**Comment by axelfontaine** [comment]
Do you have a Twitter handle? I tried to mention you in https://twitter.com/FlywayDb/status/939031159417143296 but couldn't find you and ttulka is someone else on Twitter.

**Comment by ttulka** [comment]
Well, I have (tomas_tulka) but I'm not using it, better to avoid :-)
