### ISSUE TITLE
Execute Oracle scripts using ANT

### ISSUE THREAD

**Issue by bardware** [flyway/flyway-ant#2]
I'm currrently executing SQL scripts using ANT's own SQL task. The scripts fail because they contain Oracle command line specific statements like `SET LINESIZE 200`.
I searched the internet and got the [impression](https://github.com/flyway/flyway/issues/1665) FlywayDB handles these statements.
Can I use Flyway to execute my scripts (via ant) or do I have to set up a migration to eventually use the Flyway tools at all?

**Comment by ttulka** [comment]
This doesn't look like an Ant-plugin issue. Could you please create a new issue direct in https://github.com/flyway/flyway and provide more information about, eg your error stack?

**Comment by ttulka** [comment]
Ant plugin is just a wrapper for Flyway migrations (java based). If your Sql is supported by the flyway core, you can use the Ant plugin definitely as well.

**Comment by lwasylow** [comment]
How did you setup your build xml ?
Im struggling to past error :  Flyway Error: org.flywaydb.core.api.FlywayException: Unable to instantiate JDBC driver: oracle.jdbc.OracleDriver => Check whether the jar file is present
But all jars are in classpath

**Comment by ttulka** [comment]
As there is no feedback from the issuer, I'm closing this issue.
