### ISSUE TITLE
UndoTask implementation?

### ISSUE THREAD

**Issue by hbroeder** [flyway/flyway-ant#5]
Hi,

We are using the flyway pro version. It looks like the undo task is missing from the current flyway-ant implementation. Is there a reason why flyway-ant does not implement the undo task?

/Hans

**Comment by ttulka** [comment]
Hi,
Because the Ant plugin is not officially supported, it offers only the community version functionality.

**Comment by ttulka** [comment]
Based on your question, there are some new negotiations about addind the Flyway Pro support to the Ant plugin. Please stay in touch. I will update this issue as soon as possible.

**Comment by ttulka** [comment]
@hbroeder I have just committed a basic support for Flyway Pro including the Undo task. I'd be nice when you could check out the current code, build it (`mvn package`) and provide some feedback.
The new version will be released in a few days.
Thanks a lot!

**Comment by hbroeder** [comment]
@ttulka Sure. I will find some time to do this today.

**Comment by hbroeder** [comment]
@ttulka Did some tests with the current flyway-ant -1.2.0 and flyway-core-5.1.4 pro edition code.
All works as expected. At your request I can send you - out of band this public thread - a redacted version of our tests.

**Comment by ttulka** [comment]
@hbroeder nice to hear that, thanks! I will release the 1.2.0 as soon as possible.

**Comment by ttulka** [comment]
Version 1.2.0 with the Flyway Pro support released: https://github.com/flyway/flyway-ant/releases/tag/v1.2.0
