### ISSUE TITLE
provide some info on migration from original flyway ant

### ISSUE THREAD

**Issue by teicher** [flyway/flyway-ant#6]
Hello, we currently use ant 4.0.3 to run migrations and commands onto multiple databases like
```
<target name="check-all-databases"
		<flyway:info url="jdbc:postgresql://${database.host}:${database.port}/coredb" sqlMigrationPrefix="C" outOfOrder="true"/>
		<flyway:info url="jdbc:postgresql://${database.host}:${database.port}/reportingdb" sqlMigrationPrefix="R" outOfOrder="true"/>
...
```
and I seem unable to figure out how to use the new community flyway-ant (1.4.5) from the documentation.

sqlMigrationPrefix is accepted neither as attribute to flyway:info, nor as nested element.
since ant properties are immutable, I cannot use them to switch database url and/or sqlMigrationPrefix between commands.

Cheers, Tom.

**Comment by ttulka** [comment]
Hey, as the Ant Task is setting the configuration property correctly, I guess this is a [flyway-core](https://github.com/flyway/flyway) issue. The info-task seems to ignore this attribute. Maybe you can open a new issue/question there?

**Comment by teicher** [comment]
Hello, many thanks for your reply.
Since you said it's supposed to work, I tested somewhat more thoroughly,
and indeed I found that `sqlMigrationPrefix` works as attribute (not nested), but it's
`sqlMigrationSuffix` that does not work.
And indeed you document that it's `sqlMigrationSuffixes` (plural) and then it works, so this is only a backwards-compatibility issue (`sqlMigrationSuffix` used to work in previous versions).

So unless you want to also accept `sqlMigrationSuffix` for backwards-compatibilities sake, I would suggest to add
> Please note this was called `sqlMigrationSuffix` in previous versions

to the sqlMigrationSuffixes documentation

and maybe add an example with proerties to the doc like
```
<flyway:info url="jdbc:postgresql://xxx/dbname" sqlMigrationPrefix="C" outOfOrder="true"/>
```

Thanks & Cheers

**Comment by ttulka** [comment]
Hey, thank you for your analysis, you're right, this attribute has been removed with https://github.com/flyway/flyway/issues/2218 in the flyway-core 6.0.0 Unfortunately there are no details in the doc or release notes. As this is not the only one attribute I would prefer to keep the doc clean and up-to-date with the current API. Adding all the breaking changes and notes would make it a bit cumbersome.
Nevertheless I agree with you, [the release notes](https://flywaydb.org/documentation/releaseNotes) should include these details. Maybe you can create an issue for that in flyway-core..?

**Comment by teicher** [comment]
Ok, thanks, will do.

Concerning flyway-ant, I would still suggest to add an example with ant task attributes to the doc, as currently it's not clear that this is really working:
```
<flyway:info url="jdbc:postgresql://xxx/dbname" sqlMigrationPrefix="C" outOfOrder="true"/>
```

**Comment by teicher** [comment]
https://github.com/flyway/flyway/issues/2544

**Comment by ttulka** [comment]
The example added into the [Wiki page](https://github.com/flyway/flyway-ant/wiki/Info)
